name: gen schema markdown workflow
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - uses: actions/checkout@v1
      - run: python -m pip install jsonschema2md boto3
      - run: python -m pip install

