name: gen schema markdown workflow
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - run: python -m pip install jsonschema2md boto3
      - name: Check out repo
        uses: actions/checkout@v2
      - run: jsonschema2md ./schema/pipeline-definition-schema.json ./schema/README.md

